<?php
namespace Magenest\ChapterFive\Model\Config\Source;

class CustomizeText extends \Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend
{
    public function beforeSave($object)
    {
        $attrCode = $this->getAttribute()->getAttributeCode();
        $value = $object->getData($attrCode);
        if($attrCode === 'custom_text_chapter_five') {
            $object->setData('custom_text_chapter_five', $value . " + varchar(" . strlen($value) . ")");
        }
        return parent::beforeSave($object);
    }

    public function afterLoad($object)
    {
        $attrCode = $this->getAttribute()->getAttributeCode();
        $value = $object->getData($attrCode);
        $pos = strpos($value, " ");
        $temp = substr($value, $pos);
        $result = trim($value,$temp);
        $object->setData($attrCode, $result);
        return parent::afterLoad($object); // TODO: Change the autogenerated stub
    }
}
