<?php
namespace Magenest\ChapterOne\Model\ResourceModel\Rules;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';
    protected $_eventPrefix = 'magenest_rules';

    /**
     * Define resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('Magenest\ChapterOne\Model\Rules', 'Magenest\ChapterOne\Model\ResourceModel\Rules');
    }

    public function getItems()
    {
        $this->addFieldToFilter("status", array("eq", "pending"));
        return parent::getItems(); // TODO: Change the autogenerated stub
    }

}
